// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED BY:
//
//     C:\Users\muyuanjin\.cargo\bin\regex-cli.exe generate serialize dense dfa --minimize --shrink --start-kind anchored --rustfmt --safe --reverse --captures none FILE_EXTENSION_SPLIT ./src/re/ \.(tar\.(?:gz|xz|bz2)|cpio\.(?:gz|bz2)|(?:7z|rar|zip)\.\d{3}|[^.]+)
//
// regex-cli 0.2.1 is available on crates.io.

use regex_automata::{
    dfa::dense::DFA,
    util::{lazy::Lazy, wire::AlignAs},
};

pub static FILE_EXTENSION_SPLIT: Lazy<DFA<&'static [u32]>> = Lazy::new(|| {
    static ALIGNED: &AlignAs<[u8], u32> = &AlignAs {
        _align: [],
        #[cfg(target_endian = "big")]
        bytes: *include_bytes!("file_extension_split.bigendian.dfa"),
        #[cfg(target_endian = "little")]
        bytes: *include_bytes!("file_extension_split.littleendian.dfa"),
    };
    let (dfa, _) = DFA::from_bytes(&ALIGNED.bytes).expect("serialized DFA should be valid");
    dfa
});
