[build]
rustflags = ["-Zlocation-detail=none", "-Cpanic=abort", "-Zpanic_abort_tests"]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort", "optimize_for_size"]