[build]
rustflags = ["-Zlocation-detail=none", "-Zpanic_abort_tests", "-Cpanic=abort"]

[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-Zlocation-detail=none", "-Zpanic_abort_tests", "-Cpanic=abort", "-Ctarget-feature=+crt-static"]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort", "optimize_for_size"]